FROM apache/airflow:3.3.0-python3.12

RUN pip install --no-cache-dir \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org \
    clickhouse-connect \
    pandas \
    requests \
    python-dotenv

RUN pip check